### ISSUE TITLE
add patch support for Right-To-Left languages. (such as Farsi, Arabic or Hebrew,....)

### ISSUE THREAD

**Issue by YosefJoo** [archy-linux/archy-dwm#20]

**Comment by 0x61nas** [comment]
I have a plan to apply [notitle](https://dwm.suckless.org/patches/notitle) patch to remove the title part from the bar. and use the space to display other information or just leave it empty, 'case it's a waste of space on my mind

**Comment by YosefJoo** [comment]
Oh , I can add notitle patch but the bibi patch
The effect is on all bars.

**Comment by 0x61nas** [comment]
> The effect is on all bars , I think we don’t need bidi patch if we want to apply notitle

yeah, but I don't see any chance of using any language other than English in any other bar part than the title part

**Comment by YosefJoo** [comment]
I agree with you , if u need applay patch notitle I can apply that and some patches is important 😁.
